export const DASHBOARD_CONFIG = {
  title: "NYC Airbnb Analytical Dashboard",
  eyebrow: "Task-driven D3 dashboard",
  description:
    "Ten idiom-driven views selected from the chart reports to answer the domain tasks in the midterm report.",
  dataPath: "/data/cleaned_listings.csv",
  dataSources: {
    listings: {
      path: "/data/cleaned_listings.csv",
      role: "primary",
      primaryKey: "id",
      description: "Main listing-level table used by the current dashboard.",
    },
    reviews: {
      path: "/data/cleaned_reviews.csv",
      role: "detail",
      foreignKey: "listing_id",
      joinsTo: "listings.id",
      description:
        "Review-level table. Aggregate by listing_id before joining into listings for chart-level metrics.",
    },
    calendar: {
      path: "/data/cleaned_calendar.csv",
      role: "detail",
      foreignKey: "listing_id",
      joinsTo: "listings.id",
      description:
        "Calendar-level table. Aggregate availability, booking, or price metrics by listing_id before joining.",
    },
    neighbourhoods: {
      path: "/data/neighbourhoods.geojson",
      role: "geo",
      foreignKey: "properties.neighbourhood",
      joinsTo: "listings.neighbourhood_cleansed",
      description:
        "GeoJSON neighbourhood boundaries for future D3 map views.",
    },
  },
  valueField: "price",
  dateField: "",
  numericFields: [
    "price",
    "number_of_reviews",
    "reviews_per_month",
    "review_scores_rating",
    "availability_365",
    "accommodates",
    "latitude",
    "longitude",
  ],
  booleanFields: ["price_is_outlier", "is_available", "is_booked", "available"],
  selectionFields: {
    region: "neighbourhood_group_cleansed",
    roomType: "room_type",
    scatterX: "number_of_reviews",
    scatterY: "price",
  },
  filters: [
    {
      id: "region",
      label: "Region",
      candidates: ["neighbourhood_group_cleansed", "region", "category"],
      helpText: "Dataset field used for geographic grouping.",
    },
    {
      id: "roomType",
      label: "Room type",
      candidates: ["room_type", "type", "segment"],
      helpText: "Dataset field used for listing type grouping.",
    },
  ],
  kpis: [
    {
      id: "records",
      label: "Total records",
      type: "count",
      tone: "blue",
    },
    {
      id: "valueSum",
      label: "Total price",
      type: "sum",
      field: "price",
      tone: "teal",
    },
    {
      id: "valueAverage",
      label: "Average price",
      type: "average",
      field: "price",
      tone: "slate",
    },
  ],
  chartCards: [
    {
      id: "task1MarketMap",
      badge: "Task 1",
      title: "Average price by neighbourhood",
      description: "Choropleth map. Geographic position answers where high and low price areas are located.",
      kind: "choropleth",
      interactionKey: "region",
      note: "Chosen over stacked bars because this task asks for spatial market distribution.",
    },
    {
      id: "task2OccupancyLines",
      badge: "Task 2",
      title: "Occupancy rate by month and borough",
      description: "Multi-line chart. Month order is preserved and boroughs are compared on one y scale.",
      kind: "occupancyLines",
      usesMetrics: true,
      interactionKey: "region",
      note: "Built from calendar aggregates for 2026 to avoid loading the full calendar table in the browser.",
    },
    {
      id: "task3CapacityHeatmap",
      badge: "Task 3",
      title: "Supply capacity by borough",
      description: "Heatmap. Borough and capacity group form the matrix; color encodes listing count.",
      kind: "capacityHeatmap",
      interactionKey: "region",
      note: "Chosen because it directly exposes capacity structure, not only room-type composition.",
    },
    {
      id: "task4QualityScatter",
      badge: "Task 4",
      title: "Rating vs review activity",
      description: "Bubble scatter plot. Rating, review volume, review velocity, and room type are shown together.",
      kind: "qualityScatter",
      interactionKey: "roomType",
      note: "Chosen over rating box plot because it also reveals reliable high-quality listings.",
    },
    {
      id: "task5PriceBox",
      badge: "Task 5",
      title: "Price distribution by borough and room type",
      description: "Box-and-whisker plot. IQR and median show distribution, not only a summary average.",
      kind: "priceBoxplot",
      interactionKey: "region",
      note: "Outlier prices are filtered out before computing quartiles.",
    },
    {
      id: "task6GoodDeals",
      badge: "Task 6",
      title: "Good deals: price vs rating",
      description: "Scatter plot with reference lines. Low price and high rating listings are highlighted.",
      kind: "goodDealScatter",
      interactionKey: "roomType",
      note: "Chosen because it answers the value-for-money question more directly than an outlier-only map.",
    },
    {
      id: "task7CostTrend",
      badge: "Task 7",
      title: "Capacity vs cost per guest",
      description: "Median price per guest by capacity with room-type trend lines.",
      kind: "costTrend",
      interactionKey: "roomType",
      note: "Trend lines expose economies of scale and the crossover point between room types.",
    },
    {
      id: "task8PolicyHeatmap",
      badge: "Task 8",
      title: "Occupancy by month and minimum-stay policy",
      description: "Heatmap. Seasonality and minimum-night policy are compared in one matrix.",
      kind: "policyHeatmap",
      usesMetrics: true,
      interactionKey: "none",
      note: "Chosen over a simple line chart because it adds the policy dependency dimension.",
    },
    {
      id: "task9HostPerformance",
      badge: "Task 9",
      title: "Host type performance",
      description: "Small-multiple bar chart comparing rating and occupancy for individual vs professional hosts.",
      kind: "hostPerformance",
      usesMetrics: true,
      interactionKey: "none",
      note: "Chosen over pie because the task asks about performance, not only market share.",
    },
    {
      id: "task10ReviewLanguage",
      badge: "Task 10",
      title: "Review language: praise vs complaints",
      description: "Diverging bar chart using log-odds strength for high-rating and low-rating review terms.",
      kind: "sentimentBars",
      usesMetrics: true,
      interactionKey: "none",
      note: "Chosen over word cloud because length on a shared axis is more accurate for comparison.",
    },
  ],
  interactionHint:
    "Use dropdowns to filter listings. Click region or room-type marks where available to cross-filter.",
};
