export const DASHBOARD_CONFIG = {
  title: "NYC Airbnb Analytical Dashboard",
  eyebrow: "Task-driven D3 dashboard",
  description:
    "Ten idiom-driven views selected from the chart reports to answer the domain tasks in the midterm report.",
  dataPath: "/data/cleaned_listings.csv",
  dataSources: {
    listings: {
      path: "/data/cleaned_listings.csv",
      role: "primary",
      primaryKey: "id",
      description: "Main listing-level table used by the current dashboard.",
    },
    reviews: {
      path: "/data/cleaned_reviews.csv",
      role: "detail",
      foreignKey: "listing_id",
      joinsTo: "listings.id",
      description:
        "Review-level table. Aggregate by listing_id before joining into listings for chart-level metrics.",
    },
    calendar: {
      path: "/data/cleaned_calendar.csv",
      role: "detail",
      foreignKey: "listing_id",
      joinsTo: "listings.id",
      description:
        "Calendar-level table. Aggregate availability, booking, or price metrics by listing_id before joining.",
    },
    neighbourhoods: {
      path: "/data/neighbourhoods.geojson",
      role: "geo",
      foreignKey: "properties.neighbourhood",
      joinsTo: "listings.neighbourhood_cleansed",
      description:
        "GeoJSON neighbourhood boundaries for future D3 map views.",
    },
  },
  valueField: "price",
  dateField: "",
  numericFields: [
    "price",
    "number_of_reviews",
    "reviews_per_month",
    "review_scores_rating",
    "availability_365",
    "accommodates",
    "latitude",
    "longitude",
  ],
  booleanFields: ["price_is_outlier", "is_available", "is_booked", "available"],
  selectionFields: {
    region: "neighbourhood_group_cleansed",
    roomType: "room_type",
    scatterX: "number_of_reviews",
    scatterY: "price",
  },
  filters: [
    {
      id: "region",
      label: "Region",
      candidates: ["neighbourhood_group_cleansed", "region", "category"],
      helpText: "Dataset field used for geographic grouping.",
    },
    {
      id: "roomType",
      label: "Room type",
      candidates: ["room_type", "type", "segment"],
      helpText: "Dataset field used for listing type grouping.",
    },
  ],
  kpis: [
    {
      id: "records",
      label: "Total records",
      type: "count",
      tone: "blue",
    },
    {
      id: "valueSum",
      label: "Total price",
      type: "sum",
      field: "price",
      tone: "teal",
    },
    {
      id: "valueAverage",
      label: "Average price",
      type: "average",
      field: "price",
      tone: "slate",
    },
  ],
  chartCards: [
    {
      id: "task1MarketMap",
      badge: "Task 1",
      title: "Average price by neighbourhood",
      description: "Choropleth map. Geographic position answers where high and low price areas are located.",
      kind: "choropleth",
      interactionKey: "region",
      note: "Chosen over stacked bars because this task asks for spatial market distribution.",
    },
    {
      id: "task2OccupancyLines",
      badge: "Task 2",
      title: "Occupancy rate by month and borough",
      description: "Multi-line chart. Month order is preserved and boroughs are compared on one y scale.",
      kind: "occupancyLines",
      usesMetrics: true,
      interactionKey: "region",
      note: "Built from calendar aggregates for 2026 to avoid loading the full calendar table in the browser.",
    },
    {
      id: "task3CapacityHeatmap",
      badge: "Task 3",
      title: "Room type by borough",
      description: "Stacked bar chart. Borough and room type show the supply structure directly.",
      kind: "stackedRoomTypeBars",
      interactionKey: "region",
      note: "Matches the stacked bar idiom used in the report for supply structure.",
    },
    {
      id: "task4QualityScatter",
      badge: "Task 4",
      title: "Rating distribution by borough",
      description: "Boxplot with overlaid points. Borough on x, rating on y, and the full distribution stays visible.",
      kind: "ratingBoxplot",
      interactionKey: "region",
      note: "Matches the boxplot idiom used in the report for Task 4.",
    },
    {
      id: "task5PriceBox",
      badge: "Task 5",
      title: "Price distribution by borough",
      description: "Box-and-whisker plot with room-type points. Borough and price show the distribution clearly.",
      kind: "priceBoxplot",
      interactionKey: "region",
      note: "Matches the boxplot idiom used in the report for price distribution.",
    },
    {
      id: "task6GoodDeals",
      badge: "Task 6",
      title: "Price vs rating",
      description: "Scatter plot with reference lines. Good deals and normal listings are separated by color.",
      kind: "goodDealScatter",
      interactionKey: "roomType",
      note: "Matches the report scatter for good-deal detection.",
    },
    {
      id: "task7CostTrend",
      badge: "Task 7",
      title: "Price per person by borough",
      description: "Grouped bar chart. Borough and room type compare the median cost per guest.",
      kind: "pricePerPersonGroupedBars",
      interactionKey: "roomType",
      note: "Matches the grouped bar idiom used in the report for Task 7.",
    },
    {
      id: "task8PolicyHeatmap",
      badge: "Task 8",
      title: "Occupancy by month and minimum-stay policy",
      description: "Heatmap. Seasonality and minimum-night policy are compared in one matrix.",
      kind: "policyHeatmap",
      usesMetrics: true,
      interactionKey: "none",
      note: "Chosen over a simple line chart because it adds the policy dependency dimension.",
    },
    {
      id: "task9HostPerformance",
      badge: "Task 9",
      title: "Host type performance",
      description: "Faceted bar chart comparing rating and occupancy for individual vs professional hosts.",
      kind: "hostPerformanceBars",
      usesMetrics: true,
      interactionKey: "none",
      note: "Matches the faceted bar idiom used in the report for host performance.",
    },
    {
      id: "task10ReviewLanguage",
      badge: "Task 10",
      title: "Customer experience vocabulary",
      description: "Word cloud. Term size shows frequency in reviews, and color separates praise from complaints.",
      kind: "experienceWordCloud",
      usesMetrics: true,
      interactionKey: "none",
      note: "Matches the word-cloud idiom in the report for customer experience language.",
    },
  ],
  interactionHint:
    "Use dropdowns to filter listings. Click region or room-type marks where available to cross-filter.",
};
