export const DASHBOARD_CONFIG = {
  title: "Airbnb Listing Dashboard",
  eyebrow: "React + D3 interactive example",
  description:
    "CSV dashboard with dropdown filters, KPI cards, clickable D3 charts, scatter brush selection, and live insight updates.",
  dataPath: "/data/cleaned_listings.csv",
  dataSources: {
    listings: {
      path: "/data/cleaned_listings.csv",
      role: "primary",
      primaryKey: "id",
      description: "Main listing-level table used by the current dashboard.",
    },
    reviews: {
      path: "/data/cleaned_reviews.csv",
      role: "detail",
      foreignKey: "listing_id",
      joinsTo: "listings.id",
      description:
        "Review-level table. Aggregate by listing_id before joining into listings for chart-level metrics.",
    },
    calendar: {
      path: "/data/cleaned_calendar.csv",
      role: "detail",
      foreignKey: "listing_id",
      joinsTo: "listings.id",
      description:
        "Calendar-level table. Aggregate availability, booking, or price metrics by listing_id before joining.",
    },
    neighbourhoods: {
      path: "/data/neighbourhoods.geojson",
      role: "geo",
      foreignKey: "properties.neighbourhood",
      joinsTo: "listings.neighbourhood_cleansed",
      description:
        "GeoJSON neighbourhood boundaries for future D3 map views.",
    },
  },
  valueField: "price",
  dateField: "",
  numericFields: [
    "price",
    "number_of_reviews",
    "reviews_per_month",
    "review_scores_rating",
    "availability_365",
    "accommodates",
    "latitude",
    "longitude",
  ],
  booleanFields: ["price_is_outlier", "is_available", "is_booked", "available"],
  selectionFields: {
    region: "neighbourhood_group_cleansed",
    roomType: "room_type",
    scatterX: "number_of_reviews",
    scatterY: "price",
  },
  filters: [
    {
      id: "region",
      label: "Region",
      candidates: ["neighbourhood_group_cleansed", "region", "category"],
      helpText: "Dataset field used for geographic grouping.",
    },
    {
      id: "roomType",
      label: "Room type",
      candidates: ["room_type", "type", "segment"],
      helpText: "Dataset field used for listing type grouping.",
    },
  ],
  kpis: [
    {
      id: "records",
      label: "Total records",
      type: "count",
      tone: "blue",
    },
    {
      id: "valueSum",
      label: "Total price",
      type: "sum",
      field: "price",
      tone: "teal",
    },
    {
      id: "valueAverage",
      label: "Average price",
      type: "average",
      field: "price",
      tone: "slate",
    },
  ],
  chartCards: [
    {
      id: "regionTrend",
      badge: "Chart 1",
      title: "Average price by region",
      description: "D3 line chart. Hover for details, click a point to cross-filter.",
      kind: "line",
      groupField: "neighbourhood_group_cleansed",
      metricField: "price",
      interactionKey: "region",
      note: "Click same region again to clear.",
    },
    {
      id: "roomTypeBars",
      badge: "Chart 2",
      title: "Average price by room type",
      description: "D3 bar chart. Hover for metrics, click a bar to filter.",
      kind: "bar",
      groupField: "room_type",
      metricField: "price",
      interactionKey: "roomType",
      note: "Bars update from dropdowns and other chart selections.",
    },
    {
      id: "priceReviewsScatter",
      badge: "Chart 3",
      title: "Price vs number of reviews",
      description: "D3 scatter plot. Brush a rectangle to filter the whole dashboard.",
      kind: "scatter",
      xField: "number_of_reviews",
      yField: "price",
      colorField: "room_type",
      interactionKey: "brush",
      note: "Drag on the plot to create a brush selection.",
    },
    {
      id: "regionShare",
      badge: "Chart 4",
      title: "Listing share by region",
      description: "D3 donut chart. Hover slices, click a region to cross-filter.",
      kind: "donut",
      groupField: "neighbourhood_group_cleansed",
      interactionKey: "region",
      note: "Donut is based on record count.",
    },
  ],
  interactionHint:
    "Click line points, bars, or donut slices to cross-filter. Brush scatter plot to select a numeric range.",
};
